name: shell commands
on:
  - push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo string
        run: echo "Hello"
      - name: multiline script
        run: |
          node -v
          pwd
  run-windows-command:
    runs-on: windows-latest
    #the needs flag below sets this second job to depend on the first job run
    needs: ["run-shell-command"] 
    steps:
      - name: Directory
        run: Get-Location
      - name: Directory using bash
        run: pwd
        shell: bash
        